### ISSUE TITLE
支持使用三目运算绑定不同的值吗

### ISSUE THREAD

**Issue by alguojian** [whataa/noDrawable#4]

**Comment by alguojian** [comment]
还有阴影要支持吗

**Comment by whataa** [comment]
1. 支持三目运算符，以及其它表达式，这是DataBinding的特性；例如你可以这样写：
```
drawable_solidColor=@{enable ? @color/green : @color/gray}
```
2. 阴影的话，不知道你是有什么特殊的需求吗，普通的阴影在Android5.0系统就开始就支持了，增加elevation或者translationZ属性就可以。

**Comment by alguojian** [comment]
有时候惠子额一些drawable文件，list包括了多个shape创找出一个阴影效果，，，我们支持到4.3，新属性不适配呢

**Comment by whataa** [comment]
不支持嵌套形式的drawable描述，例如你上面说的list包含多个shape组成的最终效果。
这个由布局文件的属性声明形式所限制，即不能在属性值里再定义属性，所以本方案没有说完全替代drawable资源文件，如果你有更好的属性定义方式，欢迎一起探讨。

不过对于你这种需求，noDrawable提供了诸如drawable_pressed这样的属性，方便直接引用drawable资源文件：
```
drawable_pressed="@{@drawable/list_shapes}"
```
