### ISSUE TITLE
宽度之类的属性值只能支持int整数吗，不支持小数

### ISSUE THREAD

**Issue by jsonhu** [whataa/noDrawable#6]

**Comment by whataa** [comment]
这个具体是int还是float可以查看`tech.linjiang.android.drawable.Drawables.java` 中的`create()` 方法的参数。

如果你仅指`drawable_width`，该属性确实仅支持int，因为内部是调用的 `drawable.setSize(int, int)` 方法。

**Comment by jsonhu** [comment]
好像还不支持条件表达式

**Comment by whataa** [comment]
已更新1.1.0：
所有的数值属性都支持int和float，例如 `@{0.5f}`

**Comment by jsonhu** [comment]
nice
