### ISSUE TITLE
亲，android studio 3.5 canary8 xml直接输drawable_不能联想出属性了。

### ISSUE THREAD

**Issue by wzhzai** [whataa/noDrawable#7]

**Comment by whataa** [comment]
请问其它dataBinding相关的属性（包括自定义的属性）能否联想出来？Android Studio右下角是否有红色符号在闪烁？

**Comment by wzhzai** [comment]
你好，我尝试如下代码
`@BindingAdapter("type1")
public static void setType(TextView textView, int type) {
}

@BindingAdapter("app:type2")
public static void setType2(TextView textView, int type) {
}`
可以联想出来，右下角并没有红色符号在闪烁

然后我把你的代码copy到项目中就可以联想出来了

**Comment by alguojian** [comment]
果然copy出来就可以联想了，开心，又可以愉快地划水了
